stages: 
  data_ingestion:
    cmd: python src/CNNclassifier/pipeline/stage_01_data_ingestion.py

    deps: 
      - src/CNNclassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml

    outs:
      - artifacts/data_ingestion

  prepare_base_model:
    cmd: python src/CNNclassifier/pipeline/stage_02_prepare_base_model.py

    deps:
      - src/CNNclassifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml

    params:
      - IMAGE_SIZE
      - LEARNING_RATE
      - INCLUDE_TOP
      - WEIGHTS
      - CLASSES


    outs: 
      - artifacts/prepare_base_model

  training:
    cmd: python src/CNNclassifier/pipeline/stage_03_training.py


    deps: 
      - src/CNNclassifier/pipeline/stage_03_training.py
      - src/CNNclassifier/components/prepare_callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/chicken_data
      - artifacts/prepare_base_model
      
    params: 
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
      - IMAGE_SIZE

    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python src/CNNclassifier/pipeline/stage_04_evaluation.py

    deps:
      - src/CNNclassifier/pipeline/stage_04_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/chicken_data
      - artifacts/training/model.h5
    
    params:
      - IMAGE_SIZE
      - BATCH_SIZE

    metrics:
    - score.json:
        cache: false


